# Breve Introducción a Python

Hola

In [ ]:
print("Hola mundo")

Hola mundo


## Tipos de datos primitivos

En el ámbito real, cada **objeto** se asigna a una categoría específica; de manera similar, en programación, lidiamos con *objetos que están vinculados a una **clase** particular*.

Los **tipos o clases de datos** fundamentales con los que se puede operar en Python son:



1.   Números (numbers)
2.   Cadenas (strings)
3.   Booleanos (boolean)



In [ ]:
# Los números pueden ser tipo int
type(1)

int

**Observaciones:**

*   Poner un símbolo # al inicio de la sentencia es para comentar código --> no se ejectuta
*   La función type() aplicada a cualquer objeto indica la clase o tipo de objeto



In [ ]:
# Los números pueden ser tipo float
type(4)

int

Los **operadores aritméticos** son:

Operadores aritméticos: + (suma), - (resta), * (producto), / (cociente), // (cociente división entera), % (resto división entera), ** (potencia).

In [ ]:
#Potencia
print((2+2)**2)
#Resto de división:
print( 3%2)

16
1


**Observación:**

*   La función print() imprime el resultado de operaciones o el contenido de algunos objetos.
*   La única operación que no necesita print() es el último comando de la celda, ese se imprime solo.


Los **operadores lógicos** son:

== (igual que), > (mayor que), < (menor que), >= (mayor o igual que), <= (menor o igual que), != (distinto de).

In [ ]:
print(8==9)
4<5

False


True

**Variable**

Una **variable** se define como un identificador asociado a un valor específico.

Aquí están las pautas para nombrarlas:


1.   Deben comenzar siempre con una letra, seguida de otras letras o números.
2.   No se permite el uso de palabras reservadas del lenguaje.
3.   Pueden contener los caracteres: minúsculas, mayúsculas, dígito o Guiones bajos (_).
4.   Los nombres de variables son «case-sensitive» Por ejemplo, `Respuesta` y `respuesta` son nombres diferentes.


La asignación se hace con el signo = y se borra una varible con el comando `del`



In [ ]:
#Un listado de palabras clave
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [ ]:
x = 2.923
y = 3
z = 'Hola mundo'
x
print(y)
z;


3


Algunas operaciones de asignación son:

In [ ]:
# Asignación múltiple (en la misma fila)
a1, a2 = 1, 2
print(a1)
print(a2)

# Intercambio de valores
a1, a2 = a2, a1
print(a1)
print(a2)

# Incremento (equivale a x = x + 2)
a1 += 2
print(a1)
# Decremento (equivale a x = x - 1)
a2 -= 1
print(a2)

# Valor no definido
x = None

1
2
2
1
4
0


**Cadenas de texto**:

Se escriben entre comillas sencillas ’ o dobles “.

In [ ]:
z1 = 'Hola'
z2 = 'Mundo'

Para acceder a los elementos de una cadena se usa índices entre corchetes [] empezando por 0 (primer elemento)

In [ ]:
#Para acceder a los elementos de una cadena []
print(z1[0])
print(z1[1])
print(z1[2])
print(z1[3])


H
o
l
a


**Subcadenas**

c[i:j:k] : Devuelve la subcadena de c desde el carácter con el índice i hasta el carácter anterior al índice j, tomando caracteres cada k.

In [ ]:
print(z2[0:4:2])
print(z1[0:3])

Mn
Hol


**Operaciones con cadenas**

1.   c1 + c2 : Devuelve la cadena resultado de concatenar las cadenas c1 y c2.
2.   c * n : Devuelve la cadena resultado de concatenar n copias de la cadena c.
3.   c1 in c2 : Devuelve True si c1 es una cadena concenida en c2 y False en caso contrario.
4.   c1 not in c2 : Devuelve True si c1 es una cadena no concenida en c2 y False en caso contrario.





In [ ]:
z3=z1 + ' '+ z2
print(z3)
print(5*z1)
print('a' in z1)

Hola Mundo
HolaHolaHolaHolaHola
True


**Funciones aplicadas a cadenas**
1.   len(c) : Devuelve el número de caracteres de la cadena c.
2.   c.upper() : Devuelve la cadena con los mismos caracteres que la cadena c pero en mayúsculas.
3.   c.lower() : Devuelve la cadena con los mismos caracteres que la cadena c pero en minúsculas.
4.   c.title() : Devuelve la cadena con los mismos caracteres que la cadena c con el primer carácter en mayúsculas y el resto en minúsculas.

In [ ]:
print(len(z3))
print(z3.upper())
print(z3.title())

10
HOLA MUNDO
Hola Mundo


**Observación:**
cuando a un objeto se le pone un . y luego una función, quiere decir que se está usando una función guardada en ese objeto. Esas funciones reciben el nombre de **Métodos**

**Conversión de datos primitivos simples**
Las siguientes funciones convierten un dato de un tipo en otro, siempre y cuando la conversión sea posible.

*   int() convierte a entero.
*   float() convierte a real.
*   str() convierte a cadena.
*   bool() convierte a lógico.


In [ ]:
print("Cadena a entero:")
print(int('134'))

print("Real a cadena:")
print(str(13.4))


Cadena a entero:
134
Real a cadena:
13.4


## Estructuras de datos

Aunque ya hemos explorado la sección sobre tipos de datos, ahora podemos abordar **tipos de datos más elaborados** en Python, que se presentan en forma de estructuras de datos.

 *Si concebimos estos elementos como átomos, las estructuras de datos que examinaremos serían equivalentes a moléculas.*

En otras palabras, **combinamos tipos básicos para formar estructuras más complejas**.

Abordaremos diversas estructuras de datos, como **listas, tuplas y diccionarios**.

### **Listas**

Una lista en Python se define como una **secuencia ordenada de objetos de diversos tipos**. Se crean al colocar ***los elementos entre corchetes*** [ ] y ***separarlos por comas***.

Características clave:

*   **Ordenadas**: Los elementos de la lista siguen un orden específico.

*   **Variedad de tipos**: Pueden contener elementos de diferentes tipos en una misma lista.

*   **Mutables**: Las listas son mutables, lo que significa que pueden ser modificadas durante la ejecución de un programa.

In [ ]:
#Lista vacia
print(type([]))
[]

<class 'list'>


[]

In [ ]:
#Lista con elementos diferentes
lista1 = [1, 'Hola', 2.34, True, 'Mundo']
lista1

[1, 'Hola', 2.34, True, 'Mundo']

Se pueden crear listas con la **función list()**, creando una lista con los elementos de la secuencia o colección c.

In [ ]:
list('Cadena')

['C', 'a', 'd', 'e', 'n', 'a']

**Acceso a los elementos de una lista**

Se emplean los mismos operadores de acceso que para cadenas de caracteres.

*   l[i] : Devuelve el elemento de la lista l con el índice i.

**Observación:** ***El índice del primer elemento de la lista es 0:***

In [ ]:
print(lista1[0])
lista1[3]


1


True

**Sublistas**

Al igual como ocurrió con las cadenas de caracteres, se tienen las sublistas

*   l[i:j:k] : **Devuelve la sublista** desde el elemento de l con el índice i hasta el elemento anterior al índice j, tomando elementos cada k.

In [ ]:
print(lista1[0:3])

[1, 'Hola', 2.34]


**Operaciones que no modifican una lista:**

*   len(l) : Devuelve el número de elementos de la lista l.
*   sum(l) : Devuelve la suma de los elementos de la lista l, siempre que los datos se puedan sumar.
*   dato in l : Devuelve True si el dato dato pertenece a la lista l y False en caso contrario.
*   l.index(dato) : Devuelve la posición que ocupa en la lista l el primer elemento con valor dato.
*   l.count(dato) : Devuelve el número de veces que el valor dato está contenido en la lista l.

In [ ]:
print(len(lista1))
print('Hola' in lista1)
print(lista1.index('Hola'))
lista1.count('Mundo')

5
True
1


1

**Operaciones que modifican una lista**

*   l1 + l2 : Crea una nueva lista concatenan los elementos de la listas l1 y l2.

*   l.append(dato) : Añade dato al final de la lista l.

*   l.insert(índice, dato) : Inserta dato en la posición índice de la lista l y desplaza los elementos una posición a partir de la posición índice.

*   l.remove(dato) : Elimina el primer elemento con valor dato en la lista l y desplaza los que están por detrás de él una posición hacia delante.

*   l.pop([índice]) : Devuelve el dato en la posición índice y lo elimina de la lista l, desplazando los elementos por detrás de él una posición hacia delante.

*   l.sort() : Ordena los elementos de la lista l de acuerdo al orden predefinido, siempre que los elementos sean comparables.
*   l.reverse() : invierte el orden de los elementos de la lista l.

In [ ]:
lista2 = [2, 2.3, 'Hola']

#Concatenar listas
print(lista1 + lista2)

#Agregar un elemento al final de la lista
lista1.append(-23)
print(lista1)

[1, 'Hola', 2.34, True, 'Mundo', 2, 2.3, 'Hola']
[1, 'Hola', 2.34, True, 'Mundo', -23]


### **Tuplas**

Las **tuplas** son secuencias ordenadas de objetos de diversos tipos.

Su construcción se realiza al colocar los **elementos entre paréntesis** ( ), separados por comas.

Las características distintivas de las tuplas incluyen su orden, la capacidad de **contener elementos de tipos variados** y su **inmutabilidad**, lo que significa que no pueden modificarse durante la ejecución de un programa.

Estas son comúnmente empleadas para *representar colecciones de datos con una estructura específica*, como un **vector o una matriz**.






In [ ]:
# dato tupla
type( () )

tuple

In [ ]:
# Tupla con elementos de distintos tipos
print((1, "hola", True))

# Vector
t1 = (4, 2, 1)
t1

(1, 'hola', True)


(4, 2, 1)

In [ ]:
# Matriz
t2 = ((1, 2, 3), (4, 5, 6))
t2

((1, 2, 3), (4, 5, 6))

**Operaciones de tuplas**

El acceso a los elementos en una tupla se lleva a cabo de *manera similar a como se hace en las listas*.

Además, es posible **obtener subtuplas** de la misma manera que se obtienen sublistas.

Las ***operaciones comunes en listas que no implican modificación***   también son aplicables a las tuplas.

In [ ]:
#Creación de tupla
t3 = (1, 2, 2)
print(type(t3))

#Longitud de tupla
print(len(t3))

#Indice del valor 2
print(t3.index(2))


<class 'tuple'>
3
1


### **Diccionarios**

Un diccionario es una **colección de pares** formados por una **clave** y un **valor** asociado a la clave.

Se construyen poniendo los **pares entre llaves { } separados por comas**, y separando la clave del valor con dos puntos :.


Se caracterizan por:

*   No tienen orden.
*   Pueden contener elementos de distintos tipos.
*   Son **mutables**, es decir, pueden alterarse durante la ejecución de un programa.
*   Las **claves son únicas**, es decir, no pueden repetirse en un mismo diccionario

In [ ]:
print(type({}))

# Diccionario con elementos de distintos tipos
dic1 = {'nombre':'Raúl', 'Despacho': 101, 'email':'raul.gutierrez@gmail.com'}
print("Diccionario:")
print(dic1)

# Diccionarios anidados
dic2= {'nombre_completo':{'nombre': 'Alfredo', 'Apellidos': 'Sánchez Alberca'}}
print("Diccionario anidado:")
print(dic2)


<class 'dict'>
Diccionario:
{'nombre': 'Raúl', 'Despacho': 101, 'email': 'raul.gutierrez@gmail.com'}
Diccionario anidado:
{'nombre_completo': {'nombre': 'Alfredo', 'Apellidos': 'Sánchez Alberca'}}


**Acceso a los elementos de un diccionar**.

*  d[clave] **devuelve el valor del diccionario d asociado a la clave** `clave`. Si en el diccionario no existe esa clave devuelve un error.

*  d.get(clave, valor) **devuelve el valor del diccionario d asociado a la clave** `clave`. Si en el diccionario no existe esa clave devuelve valor, y si no se especifica un valor por defecto devuelve None.

In [ ]:
dic1['Despacho']

101

Dado el diccionario creado con antelación ¿como extraigo el nombre, despacho y correo?



---



In [ ]:
#Extrayendo el nombre
print(dic1['nombre'])

#Extrayendo el despacho
print(dic1['Despacho'])
print(dic1.get('Despacho'))

#Extrayendo el email
print(dic1['email'])
print(dic1.get('email'))

#No encuentra la clave edificio y regresa 1
reg = dic1.get('Edificio','1')
type(reg)

Raúl
101
101
raul.gutierrez@gmail.com
raul.gutierrez@gmail.com


str

**Operaciones que no modifican un diccionario**


*  len(d) : Devuelve el número de elementos del diccionario d.

*   clave in d : Devuelve True si la clave clave pertenece al diccionario d y False en caso contrario.

*   d.keys() : Devuelve un **iterador** sobre las claves de un diccionario.

*   d.values() : Devuelve un **iterador** sobre los valores de un diccionario.

*   d.items() : Devuelve un **iterador** sobre los pares clave-valor de un diccionario.

Un **iterador** en Python es un objeto que devuelve una secuencia de valores, ya sea finita o infinita.

Los iteradores son una forma especial de objetos en Python que se caracterizan por ser un c**onjunto de elementos contables**

In [ ]:
#Longitud del diccionario (número de pares)
print(len(dic1))

#imprimir llaves, valores e items
print(dic1.keys())
print(dic1.values())
print(dic1.items())



3
dict_keys(['nombre', 'Despacho', 'email'])
dict_values(['Raúl', 101, 'raul.gutierrez@gmail.com'])
dict_items([('nombre', 'Raúl'), ('Despacho', 101), ('email', 'raul.gutierrez@gmail.com')])


**Operaciones que modifican un diccionario**

*  d[clave] = valor : **Añade al diccionario d el par** formado por la clave clave y el valor valor.
*  d.update(d2). **Añade los pares del diccionario d2** al diccionario d.

*  d.popitem() : Devuelve la tupla formada por la clave y el valor del último par añadido al diccionario d y lo elimina del diccionario.

*  del d[clave] : **Elimina del diccionario d** el par con la clave clave.

*  d.clear() : Elimina todos los pares del diccionario d de manera que se queda vacío.

**PREGUNTA:**

¿ Cómo agregarían la clave y valor 'Universidad' 'UAM' al diccionario dic1 y luego borrarlos?

In [ ]:
#Agregar clave 'Universidad' y valor 'UAM'
dic1['Universidad']='UAM'
print(dic1)

#Quitarlos
del dic1['Universidad']
print(dic1)

dic1.update({'Universidad':'UAM'})
dic1

{'nombre': 'Raúl', 'Despacho': 101, 'email': 'raul.gutierrez@gmail.com', 'Universidad': 'UAM'}
{'nombre': 'Raúl', 'Despacho': 101, 'email': 'raul.gutierrez@gmail.com'}


{'nombre': 'Raúl',
 'Despacho': 101,
 'email': 'raul.gutierrez@gmail.com',
 'Universidad': 'UAM'}

## Condicionales

**Condicionales (if)**

if condición1:
> bloque código

elif condición2:
> bloque código

....

else :
> bloque código


Evalúa la expresión lógica **condición1** y ejecuta el primer bloque de código si es `True`;

si no, **evalúa la siguientes condiciones** hasta **llegar a la primera** que es `True` y ejecuta el bloque de código asociado.

Si ninguna condición es `True` ejecuta el bloque de código después de else:.

Pueden aparecer ***varios bloques elif*** pero ***solo uno else al final***.

**OBSERVACION:**

***Los bloques de código deben estar indentados por 2 espacios.***


In [ ]:
edad = 80
if edad <= 18 :
  print('Menor')
elif edad > 65:
  print('Jubilado')
else:
  print('Activo')

Jubilado


**PREGUNTA:**

¿ Cómo generan un bloque de código que imprima la calificación final: NA, S, B y MB de acuerdo a la calificación numérica?

## Bucles

**Bucles iterativos (for)**

for i in secuencia:
>  bloque código

**Repite la ejecución del bloque de código** para cada elemento de la secuencia, asignado dicho elemento a i en cada repetición.

Se puede **interrumpir** en cualquier momento la ejecución del bloque de código con la instrucción `break` o **saltar** la ejecución para un determinado elemento de la secuencia con la instrucción `continue`.

**OBSERVACION:**

***El bloque de código deben estar indentado por 2 espacios.***

Se utiliza fundamentalmente para r**ecorrer colecciones** de objetos como ***cadenas, listas, tuplas o diccionarios***.



In [ ]:
palabra = 'Python'
for letra in palabra:
  print(letra)


P
y
t
h
o
n


A menudo se usan con la instrucción `range`:

*  range(fin) : Genera una secuencia de números enteros desde 0 hasta fin-1.
*  range(inicio, fin, salto) : Genera una secuencia de números enteros desde inicio hasta fin-1 con un incremento de salto.

In [ ]:
# Ejemplo con un argumento
for i in range(5):
    print(i) # prints: 0, 1, 2, 3, 4,

0
1
2
3
4


**PREGUNTA**

¿Cómo imprimo en pantalla los múltiplos del 5, empezando desde 10 y terminando en el 100?

## Funciones

Una **función** es un bloque de código que tiene asociado un nombre, de manera que cada vez que ***se quiera ejecutar el bloque de código*** basta con **invocar el nombre de la función**.

Para declarar una función se utiliza la siguiente sintaxis:

def nombre-funcion (parámetros):

> bloque código

> return objeto




In [ ]:
#Definición de la función
def bienvenida():
  print('¡Bienvenido a Python!')
  return

bienvenida()

¡Bienvenido a Python!


**Parámetros y argumentos de una función**

Una función puede recibir valores cuando se invoca a través de unas variables conocidas como **parámetros** que se definen entre paréntesis en la declaración de la función.

En el **cuerpo de la función** se pueden usar estos parámetros c**omo si fuesen variables**.

Los valores que se pasan a la ***función en una llamada o invocación*** concreta de ella se conocen como **argumentos** y se asocian a los parámetros de la declaración de la función.

In [ ]:
#Función con un parámetro
def bienvenida(nombre):
  print('¡Bienvenido a Python', nombre + '!')
  return

#Se pasa un argumento
bienvenida('Laura')


¡Bienvenido a Python Laura!


**Paso de argumentos a una función**

Los argumentos se pueden pasar de dos formas:

*   **Argumentos posicionales**: Se asocian a los parámetros de la función en ***el mismo orden que aparecen*** en la definición de la función.

*   **Argumentos nominales**: Se indica ***explícitamente el nombre del parámetro*** al que se asocia un argumento de la forma parametro = argumento.

**PREGUNTA:**

¿ Cómo genero una función donde agrego dos parámetros, el nombre y apellido para que los imprima en pantalla?

In [ ]:
#Función con dos parámetros
def bienvenida(nombre, apellido):
  print('¡Bienvenido a Python', nombre, apellido + '!')
  return

#Argumentos posicionales
bienvenida('Alfredo', 'Sánchez')

#Argumentos nominales
bienvenida(apellido = 'Sánchez', nombre = 'Alfredo')


¡Bienvenido a Python Alfredo Sánchez!
¡Bienvenido a Python Alfredo Sánchez!


**Retorno de una función**

Una función puede **devolver un objeto de cualquier tipo tras su invocación**.

Para ello el objeto a devolver debe escribirse después de la palabra reservada return. Si no se indica ningún objeto, la función no devolverá nada.

In [ ]:
#Función para calcular el área de un triángulo
def area_triangulo(base, altura):
  return base * altura / 2

area_triangulo(2, 3)

3.0

**Argumentos por defecto**

En la definición de una función se puede asignar a cada parámetro un **argumento por defecto**, de manera que si se invoca la función sin proporcionar ningún argumento para ese parámetro, ***se utiliza el argumento por defecto***.



In [ ]:
def bienvenida(nombre, lenguaje = 'Python'):
  print('¡Bienvenido al curso de', lenguaje, nombre + '!')
  return

#Sin el 2do argumento
bienvenida('Laura')

#Con el 2do argumento de forma posicional
bienvenida('Laura', 'R')


¡Bienvenido al curso de Python Laura!
¡Bienvenido al curso de R Laura!


In [ ]:
print('Hola', 'Mundo')

Hola Mundo


## Programación orientada a objetos


Python también permite la **programación orientada a objetos**, que es un paradigma de programación en la que los datos y las operaciones que pueden realizarse con esos datos se agrupan en ***unidades lógicas llamadas objetos***.



*   Los objetos suelen representar conceptos del dominio del programa, como un
estudiante, un coche, un teléfono, etc.

*   Los datos que describen las características del objeto se llaman **atributos** y son la *parte estática del objeto*.


*   Mientras que las operaciones que puede realizar el objeto se llaman **métodos** y son la *parte dinámica del objeto*.




---


Ejemplo. Una **tarjeta de crédito** puede representarse como un objeto:

*  **Atributos**: Número de la tarjeta, titular, balance, fecha de caducidad, pin, entidad emisora, estado (activa o no), etc.
*  **Métodos:** Activar, pagar, renovar, anular.



**Acceso a los atributos y métodos de un objeto**

*  dir(objeto): Devuelve una lista con los nombres de los atributos y métodos del objeto objeto.



---



Para acceder a los **atributos y métodos** de un objeto se pone el nombre del objeto seguido del operador punto y el nombre del atributo o el método.

*  objeto.atributo: **Accede al atributo** `atributo` del objeto objeto.

*  objeto.método(parámetros): **Ejecuta el método** `método `del objeto objeto con los parámetros que se le pasen.

***Ejemplo.*** Las cadenas tienen un método upper que convierte la cadena en mayúsculas. Para aplicar este método a la cadena c se utiliza la instrucción c.upper().

In [ ]:
c = 'Python'
print(c.upper())

PYTHON


**PREGUNTA:**

¿ Cuál es el método para agrear un elemento al final de una lista? Realiza un código para generar una lista con 4 elementos y agregar un elemento nuevo

In [ ]:
l =  [1, 2, 3]
l.append(4)         # Llamada al método append del objeto l (lista)
print(l)


[1, 2, 3, 4]


**Clases (class)**

**Los objetos con los mismos atributos y métodos se agrupan clases**. Las clases definen los atributos y los métodos, y por tanto, la semántica o comportamiento que tienen los objetos que pertenecen a esa clase.

Se puede pensar en una clase como **en un molde** a partir del cuál se pueden crear objetos.

Para declarar una clase se **utiliza la palabra clave `class`** seguida del nombre de la clase y dos puntos, de acuerdo a la siguiente sintaxis:

class nombre-clase:
>    atributos

>    métodos


---



*   **Los atributos se definen igual que las variables**

*  **Los métodos  se definen igual que las funciones**.

Para mayor detalle sobre crear clases y los conceptos relacionados ver:

https://aprendeconalf.es/docencia/python/manual/objetos/

## Módulos

El código de un programa en Python puede **reutilizarse** en otro importándolo.

*Cualquier fichero con código de Python reutilizable* se conoce como **módulo o librería**.

Los módulos suelen contener **funciones y clases**, pero también pueden definir variables con datos simples o compuestos (listas, diccionarios, etc), o cualquier otro código válido en Python.


---




Python permite **importar un módulo completo o sólo algunas partes de él**.

Cuando se importa un módulo completo, *el intérprete de Python ejecuta todo el código que contiene el módulo*, mientras que si solo se importan algunas partes del módulo, solo se ejecutarán esas partes.

**Importación completa de módulos (import)**

*  import M : **Ejecuta el código que contiene M y crea una referencia a él**, de manera que pueden invocarse un objeto o función f definida en él mediante la sintaxis M.f.

*  import M as N : **Ejecuta el código que contiene M y crea una referencia a él con el nombre N**, de manera que pueden invocarse un objeto o función f definida en él mediante la sintaxis N.f. *Esta forma es similar a la anterior, pero se suele usar cuando el nombre del módulo es muy largo para utilizar un alias más corto*.

**Importación parcial de módulos (from import)**


*  from M import f, g, ... :
Ejecuta el código que contiene M y crea referencias a los objetos f, g, ..., de manera que pueden ser invocados por su nombre.

**De esta manera para invocar cualquiera de estos objetos no hace falta precederlos por el nombre del módulo, basta con escribir su nombre.**

In [ ]:
#Importar módulo calendar
import calendar
print(calendar.month(2019, 4))

     April 2019
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



In [ ]:
import calendar as ca
print(ca.month(2020,5))

      May 2020
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



**Librerias estándar:**

**Módulos de la librería estándar más importantes
Python**  viene con una biblioteca de módulos predefinidos que no necesitan instalarse. Algunos de los más utilizados son:

*  **sys**: Funciones y parámetros específicos del sistema operativo.
*  **os**: Interfaz con el sistema operativo.
*  **os.path**: Funciones de acceso a las rutas del sistema.
*  **io**: Funciones para manejo de flujos de datos y ficheros.
*  **string**: Funciones con cadenas de caracteres.
*  **datetime**: Funciones para fechas y tiempos.
*  **math**: Funciones y constantes matemáticas.
*  **statistics**: Funciones estadísticas.
*  **random**: Generación de números pseudo-aleatorios.

**Otras librerías imprescindibles**

Estas librerías no vienen en la distribución estándar de Python, pero ya viene instaladas en google colab

*  **NumPy**: Funciones matemáticas avanzadas y arrays.
*   **SciPy**: Más funciones matemáticas para aplicaciones científicas.
*  **matplotlib**: Análisis y representación gráfica de datos.
*   **Pandas**: Funciones para el manejo y análisis de estructuras de datos.
*  **Request**: Acceso a internet por http.

## Librería Numpy

FUENTE: https://aprendeconalf.es/docencia/python/manual/numpy/

NumPy constituye una biblioteca especializada en Python que se centra en el **cálculo numérico y el análisis de datos**, particularmente diseñada para abordar **conjuntos extensos de datos**.

Introduce una categoría de objetos denominados **arrays**, los cuales posibilitan la representación de conjuntos de **datos homogéneos en múltiples dimensiones**, además de proporcionar funciones altamente eficientes para su manipulación.

La ventaja distintiva de NumPy en comparación con las listas predefinidas en Python **radica en la velocidad** significativamente mayor con la que se lleva a cabo el **procesamiento de los arrays**, alcanzando hasta ***50 veces más rapidez*** que las listas. Esta característica la convierte en una elección ideal para el **tratamiento de vectores y matrices** de dimensiones considerables.

**La clase de objetos array**

Un **array** es una ***estructura de datos de un mismo tipo*** organizada en forma de **tabla o cuadrícula** de distintas dimensiones.

Las dimensiones de un array también se conocen como **ejes**.

**Creación de arrays**

Para crear un array se utiliza la siguiente función de NumPy

*  `np.array(lista)` : Crea un array a partir de la **lista** o **tupla** y devuelve una referencia a él. El **número de dimensiones** del array dependerá de las listas o tuplas anidadas en lista:

Para **una lista** de valores se crea **un array de una dimensión**, también conocido como **vector**.

Para **una lista de listas** de valores se crea un **array de dos dimensiones**, también conocido como **matriz**.

Para **una lista de listas de listas** de valores se crea u**n array de tres dimensiones**, también conocido como **cubo**.

Y así sucesivamente. No hay límite en el número de dimensiones del array más allá de la memoria disponible en el sistema.

In [ ]:
import numpy as np

# Array de una dimensión
array1 = np.array([3, 4, 2])
print("Array de una dimensión:")
print(array1)

# Array de dos dimensiones
array2 = np.array([[3, 2, 2], [4, 1, 9]])
print("Array de dos dimensiones:")
print(array2)


Array de una dimensión:
[3 4 2]
Array de dos dimensiones:
[[3 2 2]
 [4 1 9]]


**Atributos de un array**

Existen varios atributos y funciones que describen las características de un array.

*  a.ndim : Devuelve el número de dimensiones del array a.

*  a.shape : Devuelve una tupla con las dimensiones del array a.

*  a.size : Devuelve el número de elementos del array a.

*  a.dtype: Devuelve el tipo de datos de los elementos del array a.

In [ ]:
#Número de dimensiones del array
print(array2.ndim)

#Dimensiones
array2.shape

2


(2, 3)

**Otras funciones útiles que permiten generar arrays son:**

*  np.empty(dimensiones) : Crea y devuelve una referencia a un **array vacío** con las **dimensiones especificadas** en la tupla dimensiones.

*  np.zeros(dimensiones) : Crea y devuelve una referencia a un **array con las dimensiones especificadas** en la tupla dimensiones cuyos elementos **son todos ceros**.

*   np.ones(dimensiones) : Crea y devuelve una referencia a **un array con las dimensiones especificadas** en la tupla dimensiones cuyos elementos son **todos unos**.

*  np.full(dimensiones, valor) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la **tupla dimensiones** cuyos elementos son todos valor.

*  np.identity(n) : Crea y devuelve una referencia a la **matriz identidad** de dimensión n.


In [ ]:
print(np.zeros(2))
print(np.zeros((2,2)))
print(np.ones((2,2)))
print(np.identity(5))

**Acceso a los elementos de un array**

Para acceder a los elementos contenidos en un array se **usan índices** al igual que para acceder a los elementos de una lista, pero indicando **los índices de cada dimensión separados por comas**.

Al igual que para listas, los índices de cada dimensión comienzan en 0.

También es posible **obtener subarrays con el operador dos puntos :** indicando el índice inicial y el siguiente al final para cada dimensión, de nuevo separados por comas.

**EJERCICIO**

Genera un array cuadrado de dos dimensiones con los números del 1 al 16.

Extrae el subarray del cuadrado de 2x2 interior de la matriz de 4x4.



---



Una posible solución es:

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array)

array[1:3,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 6,  7],
       [10, 11]])

## Librería pandas

FUENTE: https://aprendeconalf.es/docencia/python/manual/pandas/

**Pandas** es una librería de Python especializada en el ***manejo y análisis de estructuras de datos***.

Las principales características de esta librería son:


1.   Define nuevas estructuras de datos basadas en los ***arrays*** de la librería NumPy pero con nuevas funcionalidades.
2.   Permite ***leer y escribir fácilmente ficheros*** en formato ***CSV, Excel y bases de datos SQL***.
3.  Permite **acceder a los datos** mediante índices o nombres para filas y columnas.
4. Ofrece métodos para **reordenar, dividir y combinar** conjuntos de datos.
5. Permite trabajar con ***series temporales***.
6. Realiza todas estas operaciones de manera muy eficiente.

Tipos de datos de Pandas
Pandas dispone de ***tres estructuras*** de datos diferentes:

* ***Series***: Estructura de una dimensión.
* ***DataFrame***: Estructura de dos dimensiones (tablas).
* ***Panel***: Estructura de tres dimensiones (cubos).

Estas estructuras se construyen a partir de arrays de la librería **NumPy**, añadiendo nuevas funcionalidades.
También se puede crear estas estructuras al leer ficheros (archivos de datos)

**Creación de un DataFrame a partir de una lista de listas**

Para crear un DataFrame a partir de una ***lista de listas*** se utiliza el siguiente método:

*  `DataFrame(data=listas, index=lista_filas, columns=lista_columnas, dtype=lista_tipos)` : Devuelve un objeto del tipo DataFrame .

***Observación***: el `index` es como el nombre de las filas. `columns` es el nombre de las columnas.

Si no se pasa la lista de filas o de columnas se utilizan enteros empezando en 0. Si no se pasa la lista de tipos, se infiere.

In [ ]:
import pandas as pd

df = pd.DataFrame(data=[['María', 18], ['Luis', 22],
 ['Carmen', 20], ['Héctor', 21]],columns=['Nombre', 'Edad'])
print(df)

   Nombre  Edad
0   María    18
1    Luis    22
2  Carmen    20
3  Héctor    21


**EJERCICIO:**

Realicen un dataframe con dos columnas, el "Nombre" y "Apellido" de todos ustedes.

Centrándose en dataframes (marcos de datos) existen varios ***atributos*** o ***métodos*** para ver las ***características*** de un objeto tipo DataFrame.

* MÉTODO: **df.info()** : Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame df.

* ATRIBUTO **df.shape** : Devuelve una tupla con el número de filas y columnas del DataFrame df.

* ATRIBUTO **df.size** : Devuelve el número de elementos del DataFrame.

* ATRIBUTO **df.columns** : Devuelve una lista con los nombres de las columnas del DataFrame df.

* ATRIBUTO **df.index** : Devuelve una lista con los nombres de las filas del DataFrame df.

* ATRIBUTO **df.dtypes** : Devuelve una serie con los tipos de datos de las columnas del DataFrame df.

* MÉTODO **df.head(n)** : Devuelve las n primeras filas del DataFrame df.

* MÉTODO **df.tail(n)** : Devuelve las n últimas filas del DataFrame df.

In [ ]:
#Atributo para imprimir dimensiones
print(df.shape)

#Método para imprimir información
print(df.info())

#Método para imprimir el tipo de dato
print(df.dtypes)

#Atributo para el nombre de las columnas
df.columns

(4, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Nombre  4 non-null      object
 1   Edad    4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes
None
Nombre    object
Edad       int64
dtype: object


Index(['Nombre', 'Edad'], dtype='object')

**Renombrar los nombres de las filas y columnas**

Para cambiar el nombre de las filas y las columnas de un DataFrame se utiliza el siguiente método:

*  `df.rename(columns=dic_columnas, index=dic_filas)`:

Devuelve el DataFrame que resulta de renombrar las columnas indicadas en las **claves del diccionario** `dic_columnas` con sus valores y las filas indicadas en las **claves del diccionario** `dic_filas` con sus valores en el DataFrame df.

**EJERCICIO:**

Cambie  los nombres de las columnas del data frame previo para que tenga puras mayúsculas

**Accesos mediante posiciones**

*  df.iloc[i, j] : Devuelve el elemento que se encuentra en la fila i y la columna j del DataFrame df. Pueden indicarse secuencias de índices  [:,:] para obtener partes del DataFrame.

*  df.iloc[i] : Devuelve una serie con los elementos de la fila i del DataFrame df.

In [ ]:
#Imprimir elemento
print(df.iloc[1, 1])

#Imprimir sub dataframe con secuencia [:,:]
print(df.iloc[0:2,0:2])

#Imprimir la serie
print("La serie dada por la primera fila")
print(df.iloc[1])

22
  Nombre  Edad
0  María    18
1   Luis    22
La serie dada por la primera fila
Nombre    Luis
Edad        22
Name: 1, dtype: object


**Acceso a los elementos mediante nombres**

*  df.loc[fila, columna] : ***Devuelve el elemento*** que se encuentra en la fila con nombre fila y la columna de con nombre columna del DataFrame df.

*  df.loc[filas, columnas] : ***Devuelve un DataFrame*** con los elemento que se encuentra en las filas con los ***nombres de la lista filas*** y las columnas con los ***nombres de la lista columnas*** del DataFrame df.

*  df[columna] : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df.

In [ ]:
print(df)
#Las filas no le dimos nombre (es el index)

#Extraer un elemento
print("Solo un elemento:")
print(df.loc[2, 'Edad'])

#Extraer un subdataframe
print("un subdataframe:")
print(df.loc[[1,2], ['Nombre','Edad']])

#Extraer un pandas serie
print("Una serie:")
print(df['Nombre'])


NameError: name 'df' is not defined

**Añadir columnas a un DataFrame**

El procedimiento para añadir una nueva columna a un DataFrame es similar al de añadir un nuevo par a un diccionario, pero pasando los valores de la columna en una lista o serie.

*  d[nombre] = lista: Añade al DataFrame df una **nueva columna** con el nombre `nombre` y ***los valores de la lista*** `lista`. La lista debe tener el mismo tamaño que el número de filas de df.

*  d[nombre] = serie: Añade al DataFrame df una **nueva columna** con el nombre `nombre` y los valores de la serie `serie`. Si el tamaño de la serie es menor que el número de filas de df se rellena con valores NaN mientras que si es mayor se recorta.

In [ ]:
#con lista
df['Primer apellido'] = ['García', 'Fernández', 'Pérez', 'Velazquez']

#Con pandas serie
df['Segundo apellido'] = pd.Series(['Guerrero', 'Pérez', 'Olmedo', 'Hernández'])

df

Nombre  Edad Primer apellido Segundo apellido
0   María    18          García         Guerrero
1    Luis    22       Fernández            Pérez
2  Carmen    20           Pérez           Olmedo
3  Héctor    21       Velazquez        Hernández

**Ejercicio:**
Agreguen a su data frame la carrera de cada uno de ustedes