# Manejo de Módulos

Universidad Autónoma Metropolitana - Unidad Iztapalapa (UAM-I)

Maestría en Matemáticas Aplicadas e Industriales (MCMAI)

Taller de Modelado Matemático II - Parte I

Trimestre 25-P

Profesor: Dr. Alejandro Román Vásquez

Alumno: Alan Badillo Salas

In [2]:
import calendar

print(calendar.month(2025, 5))

      May 2025
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



In [3]:
import calendar as ca

print(ca.month(2025, 5))

      May 2025
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



In [4]:
from calendar import month

print(month(2025, 5))

      May 2025
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



* `sys`
* `os`
* `io`
* `string`
* `datetime`
* `math`
* `statistics`

* `numpy`
* `scipy`
* `pandas`
* `matplotlib`
* `request`

# Paquete de Numpy

In [5]:
import numpy

## Ejercicio: Matriz de $4 \times 4$ y su centro de $2 \times 2$

In [7]:
A = numpy.ones((4, 4)) * 10; A

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [8]:
A[1:3, 1:3]

array([[10., 10.],
       [10., 10.]])

In [11]:
B = (numpy.arange(16) + 1).reshape((4, 4)); B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
B[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

# Paquete de Pandas

In [13]:
import pandas

## Ejemplo: Crear un *DataFrame* desde listas

In [16]:
data1 = pandas.DataFrame({
    "Id": [1, 2, 3],
    "Fruta": ["Manzana", "Pera", "Kiwi"],
    "Precio": [45, 67, 23]
})

data1.head()

Id    Fruta  Precio
0   1  Manzana      45
1   2     Pera      67
2   3     Kiwi      23

## Ejemplo: Crear un *DataFrame* desde una matriz

In [17]:
data2 = pandas.DataFrame([
    [1, 2, 3],
    ["Manzana", "Pera", "Kiwi"],
    [45, 67, 23],
])

data2.head()

0     1     2
0        1     2     3
1  Manzana  Pera  Kiwi
2       45    67    23

In [19]:
data2 = pandas.DataFrame([
    [1, 2, 3],
    ["Manzana", "Pera", "Kiwi"],
    [45, 67, 23],
], index=[23, 24, 25], columns=["Id", "Fruta", "Precio"])

data2.head()

Id Fruta Precio
23        1     2      3
24  Manzana  Pera   Kiwi
25       45    67     23

## Ejercicio: Lista de Nombre y Apellidos

In [20]:
data3 = pandas.DataFrame({
    "Nombre": ["Alan", "Brandon", "Diego"],
    "Apellido": ["Badillo", "Gómez", "Arce"]
})

data3.head()

Nombre Apellido
0     Alan  Badillo
1  Brandon    Gómez
2    Diego     Arce

In [22]:
data4 = pandas.DataFrame(
    data=[("Alan", "Badillo"), ("Brandon", "Gómez"), ("Diego", "Arce")],
    columns=["Nombre", "Apellido"])

data4.head()

Nombre Apellido
0     Alan  Badillo
1  Brandon    Gómez
2    Diego     Arce

## Atributos y Métodos de un *DataFrame*

* `.info()`
* `.shape`
* `.size`
* `.columns`
* `.index`
* `.dtypes`
* `.head(n)`
* `.tail(n)`

## Ejercicio: Modificar las columnas a mayúsculas

In [25]:
data5 = pandas.DataFrame(
    data=[("Alan", "Badillo"), ("Brandon", "Gómez"), ("Diego", "Arce")],
    columns=["Nombre", "Apellido"])

data5.columns = data5.columns.map(str.upper)

data5.head()

NOMBRE APELLIDO
0     Alan  Badillo
1  Brandon    Gómez
2    Diego     Arce

## Acceso por mapa de índices

* `.iloc[<índice columna>]`
* `.iloc[<índice columna>, <índice fila>]`
* `.loc[<fila>]`
* `.loc[<fila>, <columna>]`

In [26]:
data1.head()

Id    Fruta  Precio
0   1  Manzana      45
1   2     Pera      67
2   3     Kiwi      23

In [27]:
data1.iloc[1]

Id           2
Fruta     Pera
Precio      67
Name: 1, dtype: object

In [29]:
data1.iloc[1, 0]

np.int64(2)

In [33]:
data1.loc[0]

Id              1
Fruta     Manzana
Precio         45
Name: 0, dtype: object

In [32]:
data1.loc[:, "Fruta"]

0    Manzana
1       Pera
2       Kiwi
Name: Fruta, dtype: object

## Columnas computadas

In [34]:
data6 = data5.copy()

data6.head()

NOMBRE APELLIDO
0     Alan  Badillo
1  Brandon    Gómez
2    Diego     Arce

In [35]:
data6["EDAD"] = 18

data6.head()

NOMBRE APELLIDO  EDAD
0     Alan  Badillo    18
1  Brandon    Gómez    18
2    Diego     Arce    18

### Ejercicio: Agregar la carrera

In [37]:
data6["CARRERA"] = ["Lic. Matemáticas Aplicadas", "Ing. Química", "Lic. Matemáticas"]

data6.head()

NOMBRE APELLIDO  EDAD                     CARRERA
0     Alan  Badillo    18  Lic. Matemáticas Aplicadas
1  Brandon    Gómez    18                Ing. Química
2    Diego     Arce    18            Lic. Matemáticas